#!/usr/bin/env python3
"""Build assets/data.js from the reference CSVs in data/.

The CSVs are the source of truth (same files as the Odoo module). External
id references (cat_D, hue_1B...) are resolved to plain codes so the site
needs no Odoo concepts at all.
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / 'data'


def read(name):
    with open(DATA / name, newline='', encoding='utf-8') as handle:
        return list(csv.DictReader(handle))


def code_of(ref, prefix):
    """'hue_1B' -> '1B'; empty stays empty."""
    return ref[len(prefix):] if ref and ref.startswith(prefix) else (ref or '')


def main():
    payload = {
        'categories': [{'code': r['code'], 'name': r['name']}
                       for r in read('gem.notation.category.csv')],
        'grades': [{'code': r['code'], 'name': r['name']}
                   for r in read('gem.notation.grade.csv')],
        'hues': [{'code': r['code'], 'name': r['name']}
                 for r in read('gem.notation.hue.csv')],
        'shapes': [{'code': r['code'], 'name': r['name']}
                   for r in read('gem.notation.shape.csv')],
        'stones': [{
            'code': r['code'],
            'name': r['name'],
            'category': code_of(r['category_id:id'], 'cat_'),
            'implied_hue': code_of(r['implied_hue_id:id'], 'hue_'),
            'default_grade': code_of(r['default_grade_id:id'], 'grade_'),
            'default_hue': code_of(r['default_hue_id:id'], 'hue_'),
            'default_shape': code_of(r['default_shape_id:id'], 'shape_'),
        } for r in read('gem.notation.stone.csv')],
    }
    body = json.dumps(payload, ensure_ascii=False, indent=1)
    out = ROOT / 'assets' / 'data.js'
    out.write_text(
        "// Generated by tools/build_data.py from data/*.csv - do not edit.\n"
        "(function (root, factory) {\n"
        "  if (typeof module === 'object' && module.exports) module.exports = factory();\n"
        "  else root.GEM_DATA = factory();\n"
        "})(typeof self !== 'undefined' ? self : this, function () {\n"
        "  return " + body + ";\n"
        "});\n", encoding='utf-8')
    print(f"{out.name}: {len(payload['stones'])} stones, "
          f"{len(payload['hues'])} hues, {len(payload['shapes'])} shapes, "
          f"{len(payload['grades'])} grades, "
          f"{len(payload['categories'])} categories")


if __name__ == '__main__':
    main()
