#!/usr/bin/env python3
"""Build assets/data.js and assets/variety-data.js from the CSVs in data/.

The CSVs are the source of truth (same files as the Odoo module). External
id references (cat_D, hue_1B...) are resolved to plain codes so the site
needs no Odoo concepts at all.
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / 'data'


def read(name):
    with open(DATA / name, newline='', encoding='utf-8') as handle:
        return list(csv.DictReader(handle))


def code_of(ref, prefix):
    """'hue_1B' -> '1B'; empty stays empty."""
    return ref[len(prefix):] if ref and ref.startswith(prefix) else (ref or '')


def module_js(global_name, payload, source):
    body = json.dumps(payload, ensure_ascii=False, indent=1)
    return (f"// Generated by tools/build_data.py from {source} - do not edit.\n"
            "(function (root, factory) {\n"
            "  if (typeof module === 'object' && module.exports) module.exports = factory();\n"
            f"  else root.{global_name} = factory();\n"
            "})(typeof self !== 'undefined' ? self : this, function () {\n"
            "  return " + body + ";\n"
            "});\n")


def variety_payload():
    """The variety system: curated dictionaries and correspondence, plus
    the usage aggregates written by tools/usage.py."""
    usage = {(r['legacy_type'], r['legacy_shade']): r
             for r in read('variety.usage.csv')}
    written = {(r['legacy_type'], r['legacy_shade']): r
               for r in read('variety.written.csv')}
    with open(DATA / 'variety.metrics.json', encoding='utf-8') as handle:
        metrics = json.load(handle)
    axes = ('colour', 'grade', 'treatment', 'effect')
    legacy = []
    for r in read('variety.legacy.csv'):
        pair = (r['legacy_type'], r['legacy_shade'])
        counts = usage.get(pair, {})
        seen = written.get(pair, {})
        legacy.append({
            'type': r['legacy_type'], 'shade': r['legacy_shade'], 'family': r['family'],
            **{axis: r[axis] for axis in axes},
            'status': r['status'], 'note': r['note'],
            'stones': int(counts.get('stones') or 0),
            'lines': int(counts.get('lines') or 0),
            'written': {'products': int(seen.get('products') or 0),
                        'bare': float(seen.get('bare') or 0),
                        'full': float(seen.get('full') or 0),
                        'forms': seen.get('forms', '')},
        })
    return {
        'categories': [{'code': r['code'], 'name': r['name']}
                       for r in read('variety.category.csv')],
        'families': [{
            'id': r['id'], 'name': r['name'], 'category': r['category'],
            'code': r['code'], 'legacy_types': r['legacy_types'].split(),
            'axes': r['axes'].split(), 'default_colour': r['default_colour'],
            'look': r['look'], 'note': r['note'],
        } for r in read('variety.family.csv')],
        'colours': [{'id': r['id'], 'name': r['name'], 'kind': r['kind'],
                     'look': r['look']} for r in read('variety.colour.csv')],
        'grades': [{'id': r['id'], 'name': r['name'], 'scale': r['scale'],
                    'look': r['look']} for r in read('variety.grade.csv')],
        'treatments': [{'id': r['id'], 'name': r['name'], 'note': r['note']}
                       for r in read('variety.treatment.csv')],
        'effects': [{'id': r['id'], 'name': r['name'], 'kind': r['kind'],
                     'look': r['look']} for r in read('variety.effect.csv')],
        'legacy_types': [{
            'code': r['legacy_type'], 'name': r['name'], 'family': r['family'],
            'colour': r['colour'], 'treatment': r['treatment'],
            'article': r['article'], 'note': r['note'],
        } for r in read('variety.legacy_type.csv')],
        'legacy_shades': [{
            'code': r['legacy_shade'], 'name': r['name'], 'family': r['family'],
            **{axis: r[axis] for axis in axes}, 'note': r['note'],
        } for r in read('variety.legacy_shade.csv')],
        'legacy': legacy,
        'metrics': metrics,
    }


def main():
    payload = {
        'categories': [{'code': r['code'], 'name': r['name']}
                       for r in read('gem.notation.category.csv')],
        'grades': [{'code': r['code'], 'name': r['name']}
                   for r in read('gem.notation.grade.csv')],
        'hues': [{'code': r['code'], 'name': r['name']}
                 for r in read('gem.notation.hue.csv')],
        'shapes': [{'code': r['code'], 'name': r['name']}
                   for r in read('gem.notation.shape.csv')],
        'stones': [{
            'code': r['code'],
            'name': r['name'],
            'category': code_of(r['category_id:id'], 'cat_'),
            'implied_hue': code_of(r['implied_hue_id:id'], 'hue_'),
            'default_grade': code_of(r['default_grade_id:id'], 'grade_'),
            'default_hue': code_of(r['default_hue_id:id'], 'hue_'),
            'default_shape': code_of(r['default_shape_id:id'], 'shape_'),
        } for r in read('gem.notation.stone.csv')],
    }
    out = ROOT / 'assets' / 'data.js'
    out.write_text(module_js('GEM_DATA', payload, 'data/gem.notation.*.csv'),
                   encoding='utf-8')
    print(f"{out.name}: {len(payload['stones'])} stones, "
          f"{len(payload['hues'])} hues, {len(payload['shapes'])} shapes, "
          f"{len(payload['grades'])} grades, "
          f"{len(payload['categories'])} categories")

    variety = variety_payload()
    out = ROOT / 'assets' / 'variety-data.js'
    out.write_text(module_js('VARIETY_DATA', variety, 'data/variety.*'),
                   encoding='utf-8')
    print(f"{out.name}: {len(variety['families'])} families, "
          f"{len(variety['colours'])} colours, {len(variety['grades'])} grades, "
          f"{len(variety['treatments'])} treatments, "
          f"{len(variety['effects'])} effects, "
          f"{len(variety['legacy'])} legacy pairs")


if __name__ == '__main__':
    main()
